In [1]:
import pandas as pd

df = pd.read_csv('train.csv')
df_geo = pd.read_csv('devices.csv')

df = df.merge(df_geo, on='deviceId', how='left')

In [2]:
df.head()

,deviceId,timedate,period,t1,t2,t3,t4,t5,t6,t7,...,t10,t11,t12,t13,x1,x2,x3,deviceType,latitude,longitude
0,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01 00:00:00,train,0.29,0.05,0.0,0.43,0.47,0.45,0.2,...,0.21,0.21,0.07,0.07,0.0,0.0,8,19,50.0,18.3
1,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01 00:05:00,train,0.29,0.05,0.0,0.39,0.46,0.45,0.2,...,0.21,0.21,0.07,0.07,0.0,0.0,8,19,50.0,18.3
2,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01 00:10:00,train,0.29,0.05,0.0,0.38,0.46,0.45,0.2,...,0.21,0.21,0.07,0.07,0.0,0.0,8,19,50.0,18.3
3,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01 00:15:00,train,0.29,0.05,0.0,0.38,0.45,0.45,0.2,...,0.21,0.21,0.07,0.07,0.0,0.0,8,19,50.0,18.3
4,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01 00:20:00,train,0.29,0.05,0.0,0.37,0.45,0.45,0.2,...,0.21,0.21,0.07,0.07,0.0,0.0,8,19,50.0,18.3

In [3]:
import numpy as np

df['deviceId'] = df['deviceId'].astype('category')
df['deviceType'] = df['deviceType'].astype('category')

numeric_features = ['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't12', 't13', 'x1', 'x3', 'latitude', 'longitude']

corr_matrix = df[numeric_features].corr().abs()
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

threshold = 0.90
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > threshold)]

print(f"{to_drop}")

numeric_features_filtered = [f for f in numeric_features if f not in to_drop]

['t6', 't12', 't13']

In [ ]:
df['timedate'] = pd.to_datetime(df['timedate'])

df['year_month'] = df['timedate'].dt.to_period('h')

features = numeric_features_filtered

agg_funcs = {feat: ['mean', 'std', 'min', 'max'] for feat in features}

agg_funcs['x2'] = ['mean']

df_hourly = df.groupby(['deviceId', 'deviceType', 'year_month'], observed=True).agg(agg_funcs).reset_index()
df_hourly.columns = ['_'.join(col).strip() if col[1] else col[0] for col in df_hourly.columns.values]

df_hourly = df_hourly.dropna()

X = df_hourly.drop(columns=['deviceId', 'year_month', 'x2_mean'])
y = df_hourly['x2_mean']

In [ ]:
X.head()

,deviceType,t1_mean,t2_mean,t3_mean,t4_mean,t5_mean,t7_mean,t8_mean,t9_mean,t10_mean,t11_mean,x1_mean,x3_mean,latitude_mean,longitude_mean
0,19,0.290000,0.05,0.0,0.372500,0.446667,0.200000,0.499167,0.394167,0.210000,0.210000,0.0,8.0,50.0,18.3
1,19,0.290000,0.05,0.0,0.418333,0.464167,0.200000,0.514167,0.408333,0.210000,0.205833,0.0,8.0,50.0,18.3
2,19,0.290000,0.05,0.0,0.447500,0.477500,0.205833,0.530833,0.390000,0.210000,0.202500,0.0,8.0,50.0,18.3
3,19,0.286667,0.05,0.0,0.392500,0.459167,0.210000,0.506667,0.403333,0.210000,0.209167,0.0,8.0,50.0,18.3
4,19,0.280000,0.05,0.0,0.445000,0.473333,0.210000,0.521667,0.415000,0.208333,0.204167,0.0,8.0,50.0,18.3

In [ ]:
from flaml import AutoML

automl = AutoML()

settings = {
    "time_budget": 5000,
    "metric": 'mae',
    "task": 'regression',
    "estimator_list": ['xgboost', 'lgbm', "catboost"]
}

automl.fit(X_train=X, y_train=y, **settings)

[flaml.automl.logger: 03-15 09:24:59] {1752} INFO - task = regression
[flaml.automl.logger: 03-15 09:24:59] {1763} INFO - Evaluation method: holdout
[flaml.automl.logger: 03-15 09:25:02] {1862} INFO - Minimizing error metric: mae
[flaml.automl.logger: 03-15 09:25:02] {1979} INFO - List of ML learners in AutoML Run: ['xgboost', 'lgbm', 'catboost']
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 0, current learner xgboost
[flaml.automl.logger: 03-15 09:25:02] {2417} INFO - Estimated sufficient time budget=657085s. Estimated necessary time budget=723s.
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.1s,	estimator xgboost's best error=0.1077,	best estimator xgboost's best error=0.1077
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.3s,	estimator lgbm's best error=0.1077,	best estimator lgbm's best error=0.1077
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 2, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.3s,	estimator lgbm's best error=0.1077,	best estimator lgbm's best error=0.1077
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 3, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.4s,	estimator lgbm's best error=0.0768,	best estimator lgbm's best error=0.0768
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 4, current learner xgboost
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.4s,	estimator xgboost's best error=0.1077,	best estimator lgbm's best error=0.0768
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.5s,	estimator lgbm's best error=0.0505,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 6, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.5s,	estimator lgbm's best error=0.0505,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 7, current learner xgboost
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.6s,	estimator xgboost's best error=0.0779,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 8, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.6s,	estimator lgbm's best error=0.0505,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 9, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.7s,	estimator lgbm's best error=0.0505,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 10, current learner lgbm
[flaml.automl.logger: 03-15 09:25:02] {2466} INFO -  at 7.8s,	estimator lgbm's best error=0.0505,	best estimator lgbm's best error=0.0505
[flaml.automl.logger: 03-15 09:25:02] {2282} INFO - iteration 11, current learner lgbm
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 7.8s,	estimator lgbm's best error=0.0451,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 12, current learner xgboost
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 7.9s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 13, current learner xgboost
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.0s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 14, current learner xgboost
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.0s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 15, current learner lgbm
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.1s,	estimator lgbm's best error=0.0451,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 16, current learner xgboost
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.1s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0451
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 17, current learner lgbm
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.5s,	estimator lgbm's best error=0.0315,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 18, current learner xgboost
[flaml.automl.logger: 03-15 09:25:03] {2466} INFO -  at 8.6s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:03] {2282} INFO - iteration 19, current learner lgbm
[flaml.automl.logger: 03-15 09:25:04] {2466} INFO -  at 9.1s,	estimator lgbm's best error=0.0315,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:04] {2282} INFO - iteration 20, current learner xgboost
[flaml.automl.logger: 03-15 09:25:04] {2466} INFO -  at 9.2s,	estimator xgboost's best error=0.0519,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:04] {2282} INFO - iteration 21, current learner xgboost
[flaml.automl.logger: 03-15 09:25:04] {2466} INFO -  at 9.2s,	estimator xgboost's best error=0.0486,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:04] {2282} INFO - iteration 22, current learner lgbm
[flaml.automl.logger: 03-15 09:25:04] {2466} INFO -  at 9.5s,	estimator lgbm's best error=0.0315,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:04] {2282} INFO - iteration 23, current learner lgbm
[flaml.automl.logger: 03-15 09:25:05] {2466} INFO -  at 9.9s,	estimator lgbm's best error=0.0315,	best estimator lgbm's best error=0.0315
[flaml.automl.logger: 03-15 09:25:05] {2282} INFO - iteration 24, current learner lgbm
[flaml.automl.logger: 03-15 09:25:05] {2466} INFO -  at 10.5s,	estimator lgbm's best error=0.0313,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:05] {2282} INFO - iteration 25, current learner lgbm
[flaml.automl.logger: 03-15 09:25:07] {2466} INFO -  at 12.0s,	estimator lgbm's best error=0.0313,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:07] {2282} INFO - iteration 26, current learner lgbm
[flaml.automl.logger: 03-15 09:25:07] {2466} INFO -  at 12.4s,	estimator lgbm's best error=0.0313,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:07] {2282} INFO - iteration 27, current learner lgbm
[flaml.automl.logger: 03-15 09:25:08] {2466} INFO -  at 13.6s,	estimator lgbm's best error=0.0313,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:08] {2282} INFO - iteration 28, current learner catboost
[flaml.automl.logger: 03-15 09:25:11] {2466} INFO -  at 15.9s,	estimator catboost's best error=0.0323,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:11] {2282} INFO - iteration 29, current learner xgboost
[flaml.automl.logger: 03-15 09:25:11] {2466} INFO -  at 16.1s,	estimator xgboost's best error=0.0486,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:11] {2282} INFO - iteration 30, current learner xgboost
[flaml.automl.logger: 03-15 09:25:11] {2466} INFO -  at 16.2s,	estimator xgboost's best error=0.0486,	best estimator lgbm's best error=0.0313
[flaml.automl.logger: 03-15 09:25:11] {2282} INFO - iteration 31, current learner lgbm
[flaml.automl.logger: 03-15 09:25:12] {2466} INFO -  at 17.0s,	estimator lgbm's best error=0.0258,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:12] {2282} INFO - iteration 32, current learner catboost
[flaml.automl.logger: 03-15 09:25:41] {2466} INFO -  at 45.8s,	estimator catboost's best error=0.0323,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:41] {2282} INFO - iteration 33, current learner xgboost
[flaml.automl.logger: 03-15 09:25:41] {2466} INFO -  at 46.4s,	estimator xgboost's best error=0.0442,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:41] {2282} INFO - iteration 34, current learner lgbm
[flaml.automl.logger: 03-15 09:25:41] {2466} INFO -  at 46.7s,	estimator lgbm's best error=0.0258,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:41] {2282} INFO - iteration 35, current learner catboost
[flaml.automl.logger: 03-15 09:25:48] {2466} INFO -  at 53.1s,	estimator catboost's best error=0.0267,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:48] {2282} INFO - iteration 36, current learner lgbm
[flaml.automl.logger: 03-15 09:25:51] {2466} INFO -  at 56.4s,	estimator lgbm's best error=0.0258,	best estimator lgbm's best error=0.0258
[flaml.automl.logger: 03-15 09:25:51] {2282} INFO - iteration 37, current learner lgbm
[flaml.automl.logger: 03-15 09:25:52] {2466} INFO -  at 57.7s,	estimator lgbm's best error=0.0241,	best estimator lgbm's best error=0.0241
[flaml.automl.logger: 03-15 09:25:52] {2282} INFO - iteration 38, current learner xgboost
[flaml.automl.logger: 03-15 09:25:53] {2466} INFO -  at 57.8s,	estimator xgboost's best error=0.0442,	best estimator lgbm's best error=0.0241
[flaml.automl.logger: 03-15 09:25:53] {2282} INFO - iteration 39, current learner lgbm
[flaml.automl.logger: 03-15 09:25:58] {2466} INFO -  at 63.5s,	estimator lgbm's best error=0.0236,	best estimator lgbm's best error=0.0236
[flaml.automl.logger: 03-15 09:25:58] {2282} INFO - iteration 40, current learner lgbm
[flaml.automl.logger: 03-15 09:25:59] {2466} INFO -  at 64.6s,	estimator lgbm's best error=0.0236,	best estimator lgbm's best error=0.0236
[flaml.automl.logger: 03-15 09:25:59] {2282} INFO - iteration 41, current learner xgboost
[flaml.automl.logger: 03-15 09:25:59] {2466} INFO -  at 64.8s,	estimator xgboost's best error=0.0425,	best estimator lgbm's best error=0.0236
[flaml.automl.logger: 03-15 09:25:59] {2282} INFO - iteration 42, current learner lgbm
[flaml.automl.logger: 03-15 09:26:01] {2466} INFO -  at 66.3s,	estimator lgbm's best error=0.0236,	best estimator lgbm's best error=0.0236
[flaml.automl.logger: 03-15 09:26:01] {2282} INFO - iteration 43, current learner catboost
[flaml.automl.logger: 03-15 09:27:32] {2466} INFO -  at 157.4s,	estimator catboost's best error=0.0267,	best estimator lgbm's best error=0.0236
[flaml.automl.logger: 03-15 09:27:32] {2282} INFO - iteration 44, current learner lgbm
[flaml.automl.logger: 03-15 09:27:34] {2466} INFO -  at 159.8s,	estimator lgbm's best error=0.0230,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:34] {2282} INFO - iteration 45, current learner xgboost
[flaml.automl.logger: 03-15 09:27:35] {2466} INFO -  at 159.9s,	estimator xgboost's best error=0.0425,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:35] {2282} INFO - iteration 46, current learner lgbm
[flaml.automl.logger: 03-15 09:27:39] {2466} INFO -  at 164.3s,	estimator lgbm's best error=0.0230,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:39] {2282} INFO - iteration 47, current learner xgboost
[flaml.automl.logger: 03-15 09:27:39] {2466} INFO -  at 164.5s,	estimator xgboost's best error=0.0386,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:39] {2282} INFO - iteration 48, current learner xgboost
[flaml.automl.logger: 03-15 09:27:39] {2466} INFO -  at 164.6s,	estimator xgboost's best error=0.0386,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:39] {2282} INFO - iteration 49, current learner lgbm
[flaml.automl.logger: 03-15 09:27:40] {2466} INFO -  at 165.7s,	estimator lgbm's best error=0.0230,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:40] {2282} INFO - iteration 50, current learner xgboost
[flaml.automl.logger: 03-15 09:27:41] {2466} INFO -  at 166.2s,	estimator xgboost's best error=0.0316,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:41] {2282} INFO - iteration 51, current learner xgboost
[flaml.automl.logger: 03-15 09:27:41] {2466} INFO -  at 166.4s,	estimator xgboost's best error=0.0316,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:41] {2282} INFO - iteration 52, current learner xgboost
[flaml.automl.logger: 03-15 09:27:45] {2466} INFO -  at 169.9s,	estimator xgboost's best error=0.0284,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:45] {2282} INFO - iteration 53, current learner xgboost
[flaml.automl.logger: 03-15 09:27:47] {2466} INFO -  at 172.5s,	estimator xgboost's best error=0.0277,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:47] {2282} INFO - iteration 54, current learner lgbm
[flaml.automl.logger: 03-15 09:27:53] {2466} INFO -  at 178.5s,	estimator lgbm's best error=0.0230,	best estimator lgbm's best error=0.0230
[flaml.automl.logger: 03-15 09:27:53] {2282} INFO - iteration 55, current learner lgbm
[flaml.automl.logger: 03-15 09:27:56] {2466} INFO -  at 181.6s,	estimator lgbm's best error=0.0212,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:27:56] {2282} INFO - iteration 56, current learner lgbm
[flaml.automl.logger: 03-15 09:27:58] {2466} INFO -  at 183.3s,	estimator lgbm's best error=0.0212,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:27:58] {2282} INFO - iteration 57, current learner lgbm
[flaml.automl.logger: 03-15 09:28:07] {2466} INFO -  at 192.3s,	estimator lgbm's best error=0.0212,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:28:07] {2282} INFO - iteration 58, current learner xgboost
[flaml.automl.logger: 03-15 09:28:10] {2466} INFO -  at 195.8s,	estimator xgboost's best error=0.0262,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:28:10] {2282} INFO - iteration 59, current learner lgbm
[flaml.automl.logger: 03-15 09:28:12] {2466} INFO -  at 197.6s,	estimator lgbm's best error=0.0212,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:28:12] {2282} INFO - iteration 60, current learner xgboost
[flaml.automl.logger: 03-15 09:28:15] {2466} INFO -  at 200.7s,	estimator xgboost's best error=0.0262,	best estimator lgbm's best error=0.0212
[flaml.automl.logger: 03-15 09:28:15] {2282} INFO - iteration 61, current learner lgbm
[flaml.automl.logger: 03-15 09:28:23] {2466} INFO -  at 208.3s,	estimator lgbm's best error=0.0205,	best estimator lgbm's best error=0.0205
[flaml.automl.logger: 03-15 09:28:23] {2282} INFO - iteration 62, current learner lgbm
[flaml.automl.logger: 03-15 09:28:31] {2466} INFO -  at 216.0s,	estimator lgbm's best error=0.0201,	best estimator lgbm's best error=0.0201
[flaml.automl.logger: 03-15 09:28:31] {2282} INFO - iteration 63, current learner xgboost
[flaml.automl.logger: 03-15 09:28:33] {2466} INFO -  at 218.3s,	estimator xgboost's best error=0.0262,	best estimator lgbm's best error=0.0201
[flaml.automl.logger: 03-15 09:28:33] {2282} INFO - iteration 64, current learner lgbm
[flaml.automl.logger: 03-15 09:28:43] {2466} INFO -  at 227.8s,	estimator lgbm's best error=0.0201,	best estimator lgbm's best error=0.0201
[flaml.automl.logger: 03-15 09:28:43] {2282} INFO - iteration 65, current learner lgbm
[flaml.automl.logger: 03-15 09:29:21] {2466} INFO -  at 266.2s,	estimator lgbm's best error=0.0152,	best estimator lgbm's best error=0.0152
[flaml.automl.logger: 03-15 09:29:21] {2282} INFO - iteration 66, current learner lgbm
[flaml.automl.logger: 03-15 09:29:29] {2466} INFO -  at 274.4s,	estimator lgbm's best error=0.0152,	best estimator lgbm's best error=0.0152
[flaml.automl.logger: 03-15 09:29:29] {2282} INFO - iteration 67, current learner xgboost
[flaml.automl.logger: 03-15 09:29:30] {2466} INFO -  at 274.9s,	estimator xgboost's best error=0.0262,	best estimator lgbm's best error=0.0152
[flaml.automl.logger: 03-15 09:29:30] {2282} INFO - iteration 68, current learner lgbm
[flaml.automl.logger: 03-15 09:30:39] {2466} INFO -  at 344.4s,	estimator lgbm's best error=0.0142,	best estimator lgbm's best error=0.0142
[flaml.automl.logger: 03-15 09:30:39] {2282} INFO - iteration 69, current learner lgbm
[flaml.automl.logger: 03-15 09:31:13] {2466} INFO -  at 378.0s,	estimator lgbm's best error=0.0142,	best estimator lgbm's best error=0.0142
[flaml.automl.logger: 03-15 09:31:13] {2282} INFO - iteration 70, current learner lgbm
[flaml.automl.logger: 03-15 09:35:07] {2466} INFO -  at 612.4s,	estimator lgbm's best error=0.0136,	best estimator lgbm's best error=0.0136
[flaml.automl.logger: 03-15 09:42:30] {2724} INFO - retrain lgbm for 443.3s
[flaml.automl.logger: 03-15 09:42:30] {2727} INFO - retrained model: LGBMRegressor(colsample_bytree=0.48261331799678525,
              learning_rate=0.11015031917089436, max_bin=255,
              min_child_samples=4, n_estimators=2743, n_jobs=-1,
              num_leaves=2347, reg_alpha=0.00382627967025703,
              reg_lambda=0.003005133478649057, verbose=-1)
[flaml.automl.logger: 03-15 09:42:30] {2009} INFO - fit succeeded
[flaml.automl.logger: 03-15 09:42:30] {2010} INFO - Time taken to find the best model: 612.4068639278412

In [ ]:
import pandas as pd
df = None
df_hourly = None
X = None
y = None

In [ ]:
df_valid = pd.read_csv('valid.csv')
df_test = pd.read_csv('test.csv')

df_combined = pd.concat([df_valid, df_test], ignore_index=True)
df_combined = df_combined.merge(df_geo, on='deviceId', how='left')

df_combined['timedate'] = pd.to_datetime(df_combined['timedate'])
df_combined['year'] = df_combined['timedate'].dt.year
df_combined['month'] = df_combined['timedate'].dt.month
df_combined['day'] = df_combined['timedate'].dt.day
df_combined['hour'] = df_combined['timedate'].dt.hour

features = numeric_features_filtered
agg_funcs = {feat: ['mean', 'std', 'min', 'max'] for feat in features}

df_combined_hourly = df_combined.groupby(['deviceId', 'deviceType', 'year', 'month', 'day', 'hour']).agg(agg_funcs).reset_index()

df_combined_hourly.columns = [
    '_'.join(col).strip() if col[1] else col[0] 
    for col in df_combined_hourly.columns.values
]

In [ ]:


X_test = df_combined_hourly.drop(columns=['deviceId', 'year', 'month', 'day', 'hour'])

predictions = automl.predict(X_test)

df_combined_hourly['hourly_prediction'] = predictions

submission = df_combined_hourly.groupby(['deviceId', 'year', 'month'])['hourly_prediction'].mean().reset_index()

submission.rename(columns={'hourly_prediction': 'prediction'}, inplace=True)

submission.to_csv('submission.csv', index=False)